worker_processes auto;
worker_rlimit_nofile $NGINX_RLIMIT_NOFILE;
error_log stderr $NGINX_LOG_LEVEL;

pid /tmp/angie/angie.pid;

events {
    worker_connections $NGINX_CONNECTIONS;
}

http {

  acme_client_path /acme;
  acme_client default $NGINX_ACME_SERVER email=$NGINX_ACME_EMAIL key_type=ecdsa key_bits=256;

  upstream nrpc_upstream {
    server $NGINX_UPSTREAM;
  }

  server {
    listen 80;
    listen $NGINX_PORT ssl;
    server_name $NGINX_SERVER_NAME;

    ssl_certificate     acme://default;
    ssl_certificate_key acme://default;

    location / {
      proxy_pass http://nrpc_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

}
