apiVersion: apps/v1
kind: DaemonSet

metadata:
  name: nrpc
  namespace: domino
  labels:
    app: nrpc

spec:
  selector:
    matchLabels:
      app: nrpc

  template:
    metadata:
      labels:
        app: nrpc

    spec:
      containers:
        - name: nrpc
          image: ghcr.io/nashcom/domino-nrpc-proxy:latest
          imagePullPolicy: Always

          env:
            - name: LANG
              value: en_US.UTF-8

            - name: NGINX_REPLACE_DOTS
              value: "on"

            - name: NGINX_MAP_DEFAULT
              value: "$nrpc_preread_server_name.domino.svc.cluster.local"

          ports:
            - name: nrpc
              containerPort: 1352
              hostPort: 1352
              protocol: TCP

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000

          readinessProbe:
            tcpSocket:
              port: 1352
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 1352
            periodSeconds: 60
            timeoutSeconds: 5
            failureThreshold: 5

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsNonRoot: true
        runAsUser: 1000

      terminationGracePeriodSeconds: 5
