worker_processes auto;
worker_rlimit_nofile $NGINX_RLIMIT_NOFILE;
error_log stderr $NGINX_LOG_LEVEL;

pid /var/nginx/nginx.pid;

events {
    worker_connections $NGINX_CONNECTIONS;
}

http {

  server {
    listen $NGINX_PORT ssl;
    server_name $NGINX_SERVER_NAME;

    ssl_certificate     $NGINX_SSL_CERT;
    ssl_certificate_key $NGINX_SSL_KEY;

    location / {
      proxy_pass http://$NGINX_UPSTREAM;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }

}
