load_module /ngx_stream_nrpc_preread_module.so;

worker_processes auto;
error_log stderr debug;

pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}


stream {

  resolver 1.1.1.1 valid=60s;

  map $nrpc_preread_server_name $name {

    ~.*\..*$  ${nrpc_preread_server_name}:1234;
    default   ${nrpc_preread_server_name}.csi-domino.com:1234;

  }

  server {
    listen      1352;
    proxy_pass  $name;
    nrpc_preread on;
    nrpc_preread_replacedots on;
  }

}


#    Log Levels
#    ----------
#    debug - Useful debugging information to help determine where the problem lies.
#    info - Informational messages that aren't necessary to read but may be good to know.
#    notice - Something normal happened that is worth noting.
#    warn - Something unexpected happened, however is not a cause for concern.
#    error - Something was unsuccessful.
#    crit - There are problems that need to be critically addressed.
#    alert - Prompt action is required.
#    emerg - The system is in an unusable state and requires immediate attention.
