worker_processes auto;
worker_rlimit_nofile $NGINX_RLIMIT_NOFILE;
error_log stderr $NGINX_LOG_LEVEL;

pid /var/nginx/nginx.pid;

events {
    worker_connections $NGINX_CONNECTIONS;
}

stream {

  resolver $NGINX_RESOLVER valid=60s;

  server {
    listen $NGINX_PORT;
    proxy_pass $NGINX_UPSTREAM;
  }

}
