apiVersion: v1
kind: Service
metadata:
  name: nrpc-metrics
  namespace: domino

spec:
  clusterIP: None

  selector:
    app: nrpc

  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
