worker_processes auto;
worker_rlimit_nofile $NGINX_RLIMIT_NOFILE;
error_log stderr $NGINX_LOG_LEVEL;

pid /var/nginx/nginx.pid;

events {
    worker_connections $NGINX_CONNECTIONS;
}

stream {
    resolver $NGINX_RESOLVER valid=60s;
    access_log $NGINX_ACCESS_LOG;

    server {
        listen $NGINX_PORT;
        proxy_pass $NGINX_UPSTREAM;
    }
}

http {
    resolver $NGINX_RESOLVER valid=60s;
    access_log $NGINX_ACCESS_LOG;

    server
    {
        listen 9100;
        server_name _;

        # no root just one specific file with full path!
        location /metrics
        {
            default_type text/plain;
            alias /tmp/nginx-metrics.prom;
        }
    }
}

