name: Cleanup GHCR

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old image versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGE: domino-nrpc-proxy
          OWNER: nashcom
        run: |
          gh api \
            "/orgs/$OWNER/packages/container/$PACKAGE/versions" \
            --paginate > versions.json

          jq -r '
            sort_by(.created_at) | reverse |
            .[1:][] | .id
          ' versions.json |
          while read ID
          do
            echo "Deleting version $ID"

            gh api \
              -X DELETE \
              "/orgs/$OWNER/packages/container/$PACKAGE/versions/$ID"
          done
